name: skript-holo
description: A properly made Skript addon for HolographicDisplays
version: 1.0.4-dh

author: Blueyescat
website: https://github.com/Blueyescat/skript-holo

depend: [Skript, DecentHolograms]
softdepend: [ProtocolLib]

main: me.blueyescat.skriptholo.SkriptHolo
api-version: 1.13
